version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ensek
      POSTGRES_PASSWORD: ensekpass
      POSTGRES_DB: ensekdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ensekdb;Username=ensek;Password=ensekpass
    ports:
      - "5000:8080"
    depends_on:
      - db
volumes:
  pgdata:
